CREATE TABLE PROFESSORES(
			IDPROFESSOR					UNIQUEIDENTIFIER			PRIMARY KEY,
			NOME						VARCHAR(150)				NOT NULL,
			TELEFONE					CHAR(15)					NOT NULL,
			EMAIL						VARCHAR(150)				NOT NULL
);

CREATE TABLE CURSOS(
			IDCURSO						UNIQUEIDENTIFIER			PRIMARY KEY,
			NOME						VARCHAR(150)				NOT NULL,
			CARGAHORARIA				INT							NOT NULL
);

CREATE TABLE TURMAS(
			IDTURMA						UNIQUEIDENTIFIER			PRIMARY KEY,
            NOME						VARCHAR(150)				NOT NULL,
            DATAINICIO					DATETIME					NOT NULL,
            HORARIO						VARCHAR(150)				NOT NULL,
			IDPROFESSOR					UNIQUEIDENTIFIER			NOT NULL,
			IDCURSO						UNIQUEIDENTIFIER			NOT NULL,
			FOREIGN KEY (IDPROFESSOR)	REFERENCES					PROFESSORES(IDPROFESSOR),
			FOREIGN KEY (IDCURSO)		REFERENCES					CURSOS(IDCURSO)
);